
[package]
name = "mog"
version = "0.1.0"
authors = [ "Ilkka Rauta" ]

[dependencies.gl]
git = "https://github.com/bjz/gl-rs.git"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"

[lib]
name = "mog"

[[bin]]
name = "app"
